"""
Alert model for InALign.

Alerts are generated by the detection pipeline when a threat, anomaly, or
policy violation is identified during an agent session.  They can be
acknowledged by operators via the dashboard.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime
from typing import Any, Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import JSON, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.database import Base


class AlertType(str, enum.Enum):
    """Categories of security alerts."""

    PROMPT_INJECTION = "prompt_injection"
    PII_DETECTED = "pii_detected"
    ANOMALOUS_BEHAVIOR = "anomalous_behavior"
    POLICY_VIOLATION = "policy_violation"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    UNAUTHORIZED_ACCESS = "unauthorized_access"
    DATA_EXFILTRATION = "data_exfiltration"


class AlertSeverity(str, enum.Enum):
    """Alert severity levels in descending order of urgency."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Alert(Base):
    """Security alert generated by the detection pipeline.

    Attributes:
        id: UUID v4 primary key (inherited).
        session_id: Identifier of the agent session that triggered the alert.
        agent_id: Identifier of the AI agent involved.
        alert_type: Category of the alert (e.g. ``prompt_injection``).
        severity: Urgency level -- ``critical``, ``high``, ``medium``, or
            ``low``.
        title: One-line human-readable summary.
        description: Longer explanation of what was detected.
        details: Arbitrary JSON payload with detection-specific metadata
            (matched patterns, confidence scores, etc.).
        is_acknowledged: Whether an operator has reviewed the alert.
        acknowledged_by: UUID of the :class:`User` who acknowledged it.
        acknowledged_at: When the alert was acknowledged.
        created_at: Row creation timestamp (inherited).
    """

    __tablename__ = "alerts"

    session_id: Mapped[str] = mapped_column(
        String(255),
        index=True,
        nullable=False,
    )
    agent_id: Mapped[str] = mapped_column(
        String(255),
        index=True,
        nullable=False,
    )
    alert_type: Mapped[AlertType] = mapped_column(
        Enum(AlertType, name="alert_type", create_constraint=True, values_callable=lambda e: [m.value for m in e]),
        index=True,
        nullable=False,
    )
    severity: Mapped[AlertSeverity] = mapped_column(
        Enum(AlertSeverity, name="alert_severity", create_constraint=True, values_callable=lambda e: [m.value for m in e]),
        index=True,
        nullable=False,
    )
    title: Mapped[str] = mapped_column(
        String(512),
        nullable=False,
    )
    description: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        default="",
    )
    details: Mapped[dict[str, Any]] = mapped_column(
        JSON,
        default=dict,
        server_default="{}",
        nullable=False,
    )
    is_acknowledged: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        server_default="false",
        nullable=False,
    )
    acknowledged_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        default=None,
    )
    acknowledged_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<Alert(id={self.id!r}, type={self.alert_type!r}, "
            f"severity={self.severity!r})>"
        )
